// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQrzsOGlPIOne8ewk43c0vs5Nj1edEcE',
    appId: '1:166935112618:web:d458a1fe54658238a259d3',
    messagingSenderId: '166935112618',
    projectId: 'crud-d489e',
    authDomain: 'crud-d489e.firebaseapp.com',
    storageBucket: 'crud-d489e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0FbJ4hQfyFvv_3QzJ9JbGor-blw-BAA',
    appId: '1:166935112618:android:bda28c0694a909f1a259d3',
    messagingSenderId: '166935112618',
    projectId: 'crud-d489e',
    storageBucket: 'crud-d489e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpvuuTP51CVO5DE8WRHsYkU4NobkRNXmM',
    appId: '1:166935112618:ios:68da0b5ca996c962a259d3',
    messagingSenderId: '166935112618',
    projectId: 'crud-d489e',
    storageBucket: 'crud-d489e.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpvuuTP51CVO5DE8WRHsYkU4NobkRNXmM',
    appId: '1:166935112618:ios:205509bad88c7ca3a259d3',
    messagingSenderId: '166935112618',
    projectId: 'crud-d489e',
    storageBucket: 'crud-d489e.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
